server:
  port: 1234

auth:
  jwt:
    publicKeyUrl: "http://localhost:8081/oauth/token/public_key"


spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    database: postgresql
  datasource:
    url: jdbc:postgresql://localhost:5432/riff
    username: postgres
    password:
    driver-class-name: org.postgresql.Driver